### ISSUE TITLE
关于文中公式10的一点小疑惑

### ISSUE THREAD

**Issue by akbkon** [cuge1995/IT-Defense#1]
您好，读了您的文章，我收益匪浅。我对于图像处理方面了解甚少，对于文中的公式10有小小的疑惑：
1. 我查到自然图像的梯度大多服从超拉普拉斯分布，这里为什么使用高斯分布呀？
2. 分布中，为什么方差取d呀？

谢谢您在百忙之中抽空查看该问题，您的回答对我来说非常重要，再次感谢！

**Comment by cuge1995** [comment]
您好，非常高兴您对我们的工作感兴趣。

首先，我们这里表达的梯度是logits对image的pixel的梯度，应该不是您说的梯度。
但是，确实如您所说，我们这里的logit对相邻pixel的梯度difference的分布应该是如同像素值difference那样满足的是laplace分布更贴合真实数据。我们将在下一个版本中改正，感谢您的指正。

其次，两个pixel的距离越远，那么他们的关联性就越低，也就是方差更大，所以pixel间的距离d是和方差是正相关的一个关系。但是真要知道具体关系的话，真得去做一个统计的分析和拟合才能知道。也许关系是sigma=d,也许是sigma=d^2....等。所以我们在那里才写的是we suppose the relationship....
