### ISSUE TITLE
Does the input transformation influence benign accuracy?

### ISSUE THREAD

**Issue by Raytsang123** [cuge1995/IT-Defense#2]

**Comment by cuge1995** [comment]
Hey, thank you for your attention and interest.
The input transformation does not cause an accuracy drop in our defense.

**Comment by Raytsang123** [comment]
您好！很高兴能收到您的回复。在您的论文 The art of defense: letting networks fool the attacker 中，您使用的input transformation是对pixel做rand permutation, 为什么随机洗牌不会对benign acc造成影响？谢谢！
顺颂秋祺




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuge1995/IT-Defense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 晚上9:20
***@***.***&gt;;
抄送:&nbsp;"Ray ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cuge1995/IT-Defense] Does the input transformation influence benign accuracy? (#2)





 
Hey, thank you for your attention and interest.
 The input transformation does not cause an accuracy drop in our defense.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuge1995** [comment]
你好，对于图片来说，Shift-invariant Resnet本身就只是tightly invariant的，所以会有点下降，你可以参照这篇论文的demo。对于点云分类网络来说，分类性能是没有下降的。
