### ISSUE TITLE
About the meaning of input size `Bx3xN`

### ISSUE THREAD

**Issue by EdisonLeeeee** [cuge1995/IT-Defense#3]
Hi,  I got interested in your paper and it is an awesome job.

But I wonder what is the meaning of  `Bx3xN`. In my view, `B` is the batch size and `3` is the channel, how about `N`?

**Comment by cuge1995** [comment]
Hi, thanks for interesting.

The `N` is number of point clouds, in the point cloud classification problems, the `N` is 1024 in most case.
